### ISSUE TITLE
Could the eslintrc file be added?

### ISSUE THREAD

**Issue by philmirez** [Durban-Designer/Fighter-Ai#4]
https://github.com/Durban-Designer/Fighter-Ai/blob/cb590260d9f059dbb5b6a11b4fb7c6ed950d4164/package.json#L29

The package.json references a `react-app`, but it doesn't seem to be within the repo. 🐼 😢

**Comment by Durban-Designer** [comment]
That’s just because I copied the package.json from a React app I’m working on. Plus I intend to use react to make the UI for the actual training utility once I get to that. It’ll be a bit this thing is still super alpha. You don’t need anything but node package manager and a npm install to run this.
